version: '3.8'

services:
  inkgist:
    build:
      context: .
      dockerfile: Dockerfile
    image: loecedas/inkgist:latest
    container_name: inkgist
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
